<?php

$movies = [
    [
        "id" => 1,
        "title" => "Weapons",
        "year" => 2025,
        "rated" => "R",
        "director" => "Zach Cregger",
        "genre" => "Dark comedy, Psychological Horror",
        "poster" => "/components/movies/weapons.png",
        "hover-info" => "Hovering here for some info",
        "synopsis" => "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.",
        "trailer" => "",
        "media" => [],
        "actors" => []
    ],
    [
        "id" => 2,
        "title" => "Trick r' Treat",
        "year" => 2007,
        "rated" => "11",
        "director" => "Michael Dougherty",
        "genres" => ["Dark comedy", "Slasher horror", "Monster horror"],
        "poster" => "/components/movies/trick r treat.jpg",
        "hover-info" => "Four intertwined stories that all take place on Halloween in a small town where the residents discover that ghosts may actually exist.",
        "synopsis" => "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.",
        "trailer" => "https://www.youtube.com/embed/AoBx7F-q2CA?autoplay=1&mute=1&controls=0",
        "media" => [
            "/media/trick/1.png",
            "/media/trick/2.png",
            "/media/trick/3.png",
            "/media/trick/4.png",
        ],
        "actors" => ["Dylan Baker", "Rochelle Aytes", "Quinn Lord", "Brett Kelly", "Isabelle Deluce"],
    ],
    [
        "id" => 3,
        "title" => "Good Boy",
        "year" => 2025,
        "rated" => "R",
        "director" => "Zach Cregger",
        "genre" => "Dark comedy, Psychological Horror",
        "poster" => "/components/movies/good boy.png",
        "hover-info" => "Hovering here for some info",
        "synopsis" => "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.",
        "trailer" => "",
        "media" => [],
        "actors" => []
    ],
    [
        "id" => 4,
        "title" => "The Sinners",
        "year" => 2025,
        "rated" => "R",
        "director" => "Zach Cregger",
        "genre" => "Dark comedy, Psychological Horror",
        "poster" => "/components/movies/sinners.png",
        "hover-info" => "Hovering here for some info",
        "synopsis" => "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.",
        "trailer" => "",
        "media" => [],
        "actors" => []
    ],
    [
        "id" => 5,
        "title" => "Scream 6",
        "year" => 2025,
        "rated" => "R",
        "director" => "Zach Cregger",
        "genre" => "Dark comedy, Psychological Horror",
        "poster" => "/components/movies/scream 6.png",
        "hover-info" => "Hovering here for some info",
        "synopsis" => "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.",
        "trailer" => "",
        "media" => [],
        "actors" => []
    ],
];
