<?php

$movies = [
    [
        "id" => 1,
        "title" => "Weapons",
        "year" => 2025,
        "rated" => "R",
        "director" => "Zach Cregger",
        "genres" => ["Dark comedy", "Psychological Horror"],
        "poster" => "./components/movies/weapons.png",
        "hover-info" => "A horror-mystery about a small town where 17 children vanish overnight at 2:17 a.m",
        "synopsis" => [
            "In the small town of Maybrook, 17 third-grade students mysteriously vanish on the same night at exactly 2:17 a.m., leaving only one child alive: a boy named Alex.",
            "As suspicion and grief spread, a teacher (suspended and shamed), a desperate father of one missing child, a troubled cop, and others begin investigating — only to discover the horrifying truth: a reclusive relative named Gladys is behind it all. Through ritualistic witchcraft involving hair, sticks, and personal items, Gladys enchants Alex’s classmates and traps them in a basement to feed on their life force and prolong her own life.",
            "In the climax, Alex — forced into aiding Gladys — finally turns her own spell against her. The children break free, hunt down Gladys en masse, and tear her apart. The missing kids are rescued; though traumatized, some begin to recover.",
            "At its core, “Weapons” transforms an uncanny school-disappearance mystery into a chilling witch-craft horror, using its fragmented, multi-perspective story structure to slowly reveal the real terror hidden beneath suburban normality.",
        ],
        "trailer" => "https://www.youtube.com/watch?v=OpThntO9ixc",
        "actors" => ["Scarlett Sher", "Julia Garner", "Cary Christopher"],
        "media" => [
            "./media/wepons/1.jpeg",
            "./media/wepons/2.jpeg",
            "./media/wepons/3.jpeg",
            "./media/wepons/4.jpg",
        ]
    ],
    [
        "id" => 2,
        "title" => "Trick r' Treat",
        "year" => 2007,
        "rated" => "11",
        "director" => "Michael Dougherty",
        "genres" => ["Dark comedy", "Slasher horror", "Supernatural horror", "Monster horror", "Comedy", "Horror"],
        "poster" => "./components/movies/trick-r-treat.jpg",
        "hover-info" => "Interconnected Halloween horror tales with deadly twists.",
        "synopsis" => [
            "Five Halloween stories: A principal has a secret life, a virgin is looking for her first time, a group of kids pull a prank, a woman who loathes Halloween does not respect the rules and a mean old man meets a demonic trick-or-treater.",
            "Set on Halloween night in a small American town, Trick ’r Treat weaves together four interlocking stories that explore the dark, twisted side of the holiday. The tales range from a school principal with a deadly secret, to a group of teenagers encountering a vengeful spirit, to a couple who discovers that one child is far more sinister than they expected, and to a mysterious stranger who enforces Halloween traditions with brutal efficiency. Central to the film is Sam, a pint-sized trick-or-treater in orange pajamas, who silently ensures that Halloween rules are obeyed.",
        ],
        "trailer" => "https://www.youtube.com/embed/AoBx7F-q2CA?autoplay=1&mute=1&controls=0",
        "actors" => ["Dylan Baker", "Rochelle Aytes", "Quinn Lord"],
        "media" => [
            "./media/trick/1.png",
            "./media/trick/2.png",
            "./media/trick/3.png",
            "./media/trick/4.png",
            "./media/trick/5.png",
        ]
    ],
    [
        "id" => 3,
        "title" => "Good Boy",
        "year" => 2025,
        "rated" => "15",
        "director" => "Ben Leonberg",
        "genres" => ["Supernatural Horror", "Thriller"],
        "poster" => "./components/movies/good-boy.png",
        "hover-info" => "A haunted-house told entirely from the POV of a loyal dog, who senses supernatural forces.",
        "synopsis" => [
            "Good Boy (2025) is a supernatural horror film told entirely from the perspective of a dog, a Nova Scotia Duck Tolling Retriever named Indy. After his owner Todd, who suffers from a serious lung illness, moves them into his late grandfather’s isolated farmhouse, Indy immediately senses that something is deeply wrong.",
            "Strange noises echo through empty rooms, shadows move where no one stands, and unseen forces seem to stalk the house. Because the story unfolds strictly through the dog’s senses, the film builds tension through heightened sound, distorted visuals, and instinctual fear rather than dialogue or exposition. As the haunting intensifies, Todd’s health worsens and his behavior grows increasingly unstable, leaving Indy to navigate a world he doesn’t understand while trying desperately to protect the human he loves.",
            "The film blends emotional vulnerability with atmospheric, creeping horror, turning a familiar haunted-house story into an intimate, unsettling experience seen through the loyal but limited perspective of a pet.",
        ],
        "trailer" => "https://www.youtube.com/watch?v=VFqG99KuPV8",
        "actors" => ["Indy", "Shane Jensen", "Arielle Friedman"],
        "media" => [
            "./media/good-boy/1.jpg",
            "./media/good-boy/2.jpg",
            "./media/good-boy/3.jpg",
            "./media/good-boy/4.jpg",
        ]
    ],
    [
        "id" => 4,
        "title" => "Sinners",
        "year" => 2025,
        "rated" => "15",
        "director" => "Ryan Coogler",
        "genres" => ["Folk Horror", "Period Drama", "Supernatural Horror"],
        "poster" => "./components/movies/sinners.png",
        "hover-info" => "Twin brothers return home in 1930s Mississippi, only to awaken an ancient evil.",
        "synopsis" => "The film follows Elijah 'Smoke' and Elias 'Stack' Moore, who return to Clarksdale, Mississippi, after working for the Chicago mob. They use their ill-gotten gains to buy an abandoned sawmill and turn it into a juke joint for the local Black community. Their plans are complicated when they are confronted by a supernatural evil that has infiltrated their town.",
        "trailer" => "https://www.youtube.com/watch?v=bKGxHflevuk",
        "actors" => ["Miles Caton", "Saul Williams", "Andrene Ward-Hammond"],
        "media" => [
            "./media/sinners/1.jpg",
            "./media/sinners/2.jpg",
            "./media/sinners/3.jpg",
            "./media/sinners/4.jpg",
        ]
    ],
    [
        "id" => 5,
        "title" => "Scream VI",
        "year" => 2023,
        "rated" => "15",
        "director" => ["Matt Bettinelli-Olpin", "Tyler Gillett"],
        "genres" => ["Dark comedy", "Slasher Horror", "Suspense Mystery"],
        "poster" => "./components/movies/scream-iv.jpg",
        "hover-info" => "The survivors face a deadlier Ghostface in New York City.",
        "synopsis" => [
            "After the traumatic events that shook their hometown, the surviving protagonists from the previous film relocate to New York City hoping for a fresh start. But when a new masked killer emerges, they’re forced to confront their fears once more — Ghostface reappears, stalking them through the city’s streets and subways, turning the urban surroundings into a house of horrors. As panic spreads, the survivors must band together, struggle with distrust, guilt, and grief, and fight to stay alive in a world where no place feels safe anymore.",
            "Scream VI blends slasher violence with psychological horror and clever callbacks to its legacy — the danger is immediate and brutal, but there’s also constant tension around “who can we trust?” The film explores trauma, survival, and whether the ghosts of the past can truly be escaped.",
        ],
        "trailer" => "https://www.youtube.com/watch?v=h74AXqw4Opc",
        "actors" => ["Courteney Cox", "Melissa Barrera", "Jenna Ortega"],
        "media" => [
            "./media/scream/1.jpg",
            "./media/scream/2.jpg",
            "./media/scream/3.jpg",
            "./media/scream/4.jpg",
        ]
    ],
];


$retroRuns = [
    [
        "id" => 1,
        "title" => "Creature from the Black Lagoon",
        "year" => 1954,
        "rated" => "15",
        "director" => "Jack Arnold",
        "genres" => ["Monster Horror", "Horror", "Sci-Fi"],
        "poster" => "./components/movies/creature-from-the-black-lagoon.jpg",
        "hover-info" => "A strange prehistoric beast lurks in the depths of the Amazonian jungle",
        "synopsis" => [],
        "trailer" => "https://www.youtube.com/watch?v=rXRXTaQ6Iuw",
        "actors" => ["Richard Carlson", "Julie Adams", "Richard Denning"],
        "media" => [
            "./media/creature-black-lagoon/1.jpg",
            "./media/creature-black-lagoon/2.jpg",
            "./media/creature-black-lagoon/3.jpg",
            "./media/creature-black-lagoon/4.jpg",
        ]
    ],
    [
        "id" => 2,
        "title" => "Attack of the 50Ft. Woman",
        "year" => 1958,
        "rated" => "11",
        "director" => "Nathan Juran",
        "genres" => ["B-Horror", "Kaiju", "Drama", "Horror", "Sci-Fi"],
        "poster" => "./components/movies/Attackofthe50ftwoman.jpg",
        "hover-info" => "When an abused socialite grows to giant size because of an alien encounter",
        "synopsis" => [],
        "trailer" => "https://www.youtube.com/watch?v=dlRJbC0Bw3o",
        "actors" => ["Allison Hayes", "William Hudson", "Yvette Vickers"],
        "media" => [
            "./media/attack-50ft-woman/1.png",
            "./media/attack-50ft-woman/2.png",
            "./media/attack-50ft-woman/3.png",
            "./media/attack-50ft-woman/4.png",
        ]
    ],
    [
        "id" => 3,
        "title" => "Mars Attacks!",
        "year" => 1996,
        "rated" => "11",
        "director" => "Tim Burton",
        "genres" => ["Alien Invasion", "Dark Comedy", "Parody", "Satire", "Space Sci-Fi", "Comedy", "Sci-Fi"],
        "poster" => "./components/movies/mars-attack.jpg",
        "hover-info" => "Earth is invaded by Martians with unbeatable weapons and a cruel sense of humor.",
        "synopsis" => [],
        "trailer" => "https://www.youtube.com/watch?v=41ZzO1hW6yw",
        "actors" => ["Jack Nicholson", "Pierce Brosnan", "Sarah Jessica Parker"],
        "media" => [
            "./media/mars-attack/1.jpg",
            "./media/mars-attack/2.jpg",
            "./media/mars-attack/3.jpg",
            "./media/mars-attack/4.jpg",
        ]
    ],
    [
        "id" => 4,
        "title" => "Killer Klowns from Outer Space",
        "year" => 1988,
        "rated" => "7",
        "director" => "Stephen Chiodo",
        "genres" => ["Alien Invasion", "B-Horror", "Dark Comedy", "Monster Horror", "Parody", "Supernatural Horror"],
        "poster" => "./components/movies/killer-klowns-outer-space.jpg",
        "hover-info" => "Aliens who look like clowns come from outer space and terrorize a small town.",
        "synopsis" => [],
        "trailer" => "https://www.youtube.com/watch?v=ETiSMS4i1as",
        "actors" => ["Grant Cramer", "Suzanne Snyder", "John Allen Nelson"],
        "media" => [
            "./media/killer-klowns-outer-space/1.jpg",
            "./media/killer-klowns-outer-space/2.jpg",
            "./media/killer-klowns-outer-space/3.jpg",
            "./media/killer-klowns-outer-space/4.png",
        ]
    ],
    [
        "id" => 5,
        "title" => "Dark Water",
        "year" => 2005,
        "rated" => "15",
        "director" => "Walter Salles",
        "genres" => ["Supernatural Horror", "Drama", "Horror", "Mystery"],
        "poster" => "./components/movies/dark-water.jpg",
        "hover-info" => "A mother and daughter, still wounded, hole up in a run-down apartment building...",
        "synopsis" => [],
        "trailer" => "https://www.youtube.com/watch?v=t24DuU9TXRM",
        "actors" => ["Jennifer Connelly", "Ariel Gade", "John C. Reilly"],
        "media" => [
            "./media/dark-water/1.jpg",
            "./media/dark-water/2.jpg",
            "./media/dark-water/3.jpg",
            "./media/dark-water/4.jpg",
        ]
    ],
];
$upcoming = [
    [
        "id" => 1,
        "title" => "Scream 7",
        "year" => 2026,
        "rated" => "15",
        "director" => "Kevin Williamson",
        "genres" => ["Slasher horror", "Whodunnit", "Horror", "Mystery"],
        "poster" => "./components/movies/scream 7.png",
        "hover-info" => "When a new Ghostface killer emerges in the town where Sidney Prescott has built a new life, her darkest fears are realized as her daughter becomes the next target.",
        "synopsis" => [],
        "trailer" => "https://www.youtube.com/watch?v=UJrghaPJ0RY&t=1s",
        "actors" => ["Neve Campbell", "Courteney Cox", "Isabel May", "Jasmin Savoy Brown"],
        "media" => [
            "./media/creature-black-lagoon/1.jpg",
            "./media/creature-black-lagoon/2.jpg",
            "./media/creature-black-lagoon/3.jpg",
            "./media/creature-black-lagoon/4.jpg",
        ]
    ],
    [
        "id" => 2,
        "title" => "Psycho Killer",
        "year" => 2026,
        "rated" => "15",
        "director" => "Gavin Polone",
        "genres" => ["Folk horror", "Slasher horror", "Crime", "Horror", "Thriller"],
        "poster" => "./components/movies/psycho-killer.png",
        "hover-info" => "A police officer tracks a killer after her husband, a highway patrolman, becomes one of his victims.",
        "synopsis" => [],
        "trailer" => "https://www.youtube.com/watch?v=pwq8gwdVxts",
        "actors" => ["Neve Campbell", "Courteney Cox", "Isabel May", "Jasmin Savoy Brown"],
        "media" => [
            "./media/creature-black-lagoon/1.jpg",
            "./media/creature-black-lagoon/2.jpg",
            "./media/creature-black-lagoon/3.jpg",
            "./media/creature-black-lagoon/4.jpg",
        ]
    ],
    [
        "id" => 3,
        "title" => "Clayface",
        "year" => 2026,
        "rated" => "15",
        "director" => "James Watkins",
        "genres" => ["Body horror", "Folk horror", "Psychological horror", "Monster horror", "Showbiz drama", "Action"],
        "poster" => "./components/movies/clayface.png",
        "hover-info" => "A shape-shifting creature made of magical clay haunts Gotham City, alternating between villain and ally of Batman. Multiple tragic figures have taken on the Clayface mantle over the years.",
        "synopsis" => [],
        "trailer" => "https://www.youtube.com/watch?v=UJrghaPJ0RY&t=1s",
        "actors" => ["Neve Campbell", "Courteney Cox", "Isabel May", "Jasmin Savoy Brown"],
        "media" => [
            "./media/creature-black-lagoon/1.jpg",
            "./media/creature-black-lagoon/2.jpg",
            "./media/creature-black-lagoon/3.jpg",
            "./media/creature-black-lagoon/4.jpg",
        ]
    ],
    [
        "id" => 4,
        "title" => "Return to Silent Hill",
        "year" => 2026,
        "rated" => "15",
        "director" => "Christophe Gans",
        "genres" => ["Slasher horror", "Whodunnit", "Horror", "Mystery"],
        "poster" => "./components/movies/return-to-silent-hill.png",
        "hover-info" => "When a mysterious letter calls him back to Silent Hill in search of his lost love, James finds a once-recognizable town and encounters terrifying figures both familiar and new, and begins to question his own sanity.",
        "synopsis" => [],
        "trailer" => "https://www.youtube.com/watch?v=UJrghaPJ0RY&t=1s",
        "actors" => ["Neve Campbell", "Courteney Cox", "Isabel May", "Jasmin Savoy Brown"],
        "media" => [
            "./media/creature-black-lagoon/1.jpg",
            "./media/creature-black-lagoon/2.jpg",
            "./media/creature-black-lagoon/3.jpg",
            "./media/creature-black-lagoon/4.jpg",
        ]
    ],
    [
        "id" => 5,
        "title" => "Send Help",
        "year" => 2026,
        "rated" => "15",
        "director" => "Kevin Williamson",
        "genres" => ["Slasher horror", "Whodunnit", "Horror", "Mystery"],
        "poster" => "./components/movies/send-help.png",
        "hover-info" => "Two colleagues become stranded on a deserted island, the only survivors of a plane crash. On the island, they must overcome past grievances and work together to survive, but ultimately, it's a battle of wills and wits to make it out alive.",
        "synopsis" => [],
        "trailer" => "https://www.youtube.com/watch?v=UJrghaPJ0RY&t=1s",
        "actors" => ["Neve Campbell", "Courteney Cox", "Isabel May", "Jasmin Savoy Brown"],
        "media" => [
            "./media/creature-black-lagoon/1.jpg",
            "./media/creature-black-lagoon/2.jpg",
            "./media/creature-black-lagoon/3.jpg",
            "./media/creature-black-lagoon/4.jpg",
        ]
    ],
];
